name: Ruby

on:
  push: {} 
  schedule:
    - cron: '0 10 */7 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Test
      run: |
        gem install awesome_bot
        awesome_bot README.md --allow-ssl --white-list ohler55/ojg,jsonvat.com,myjson.com

